# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ytktest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'YTKNetwork'
  # Pods for ytktest

  target 'ytktestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ytktestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
