# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SJDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SJNetwork'
pod 'AFNetworking'
  # Pods for SJDemo

  target 'SJDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SJDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
