# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YtkNetDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'YTKNetwork'
  # Pods for YtkNetDemo

  target 'YtkNetDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YtkNetDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
